### PR TITLE
Set d.p. on data frame feeding the reactables and the downloads in Su…

### PR DESCRIPTION
**Pull request by rmbielby**
### Overview
Have set the d.p. on the proportion data being fed into the reactables and downloads (i.e. in the reactive element) to 3dp (i.e. 1dp when converted to percentages). This was mainly to ensure the downloaded match the data displayed in the app, but should also make the shinytest outputs more manageable in places.

I've also added some text below the download buttons as follows:

SubjectbyIndustryHelpText IndustrybySubjectHelpText

Expected shinytest results have had some minor updates to reflect the d.p. limits where proportions are included in the shinytest output.

### CODE REVIEW

**Comment by chfoster** [comment]
I'm wondering whether we should also *100? What do you think @rmbielby ? Don't have to do that

**Comment by rmbielby** [comment]
It's easy enough to do if you'd rather have it set up that way. It probably would make it a little more immediate to understand, whereas the decimal fraction proportions will probably require a double take.

**Comment by chfoster** [comment]
Okay let's do that then merge?

**Review by chfoster — CHANGES_REQUESTED** [review]
*100 the decimals for download docs

**Review by chfoster — APPROVED** [review]

**Pull request merged**
