### PR TITLE
Created reactive wrappers for significant processing chunks + bugfix for startup errors

### PR DESCRIPTION
**Pull request by rmbielby**
Created reactive wrappers for significant processing chunks + bugfix for startup errors

### CODE REVIEW

**Comment by chfoster** [comment]
Can we make the subject dropdown start with 'All' selected in the industry flow tab?

**Comment by chfoster** [comment]
Might not be for this branch but is there a way to have some sort of loading symbol while charts & text are loading?

**Review by chfoster — APPROVED** [review]
I've just added 2 comments but this all looks good to me!

**Comment by rmbielby** [comment]
Have re-ordered the subject input lists on all 3 relevant tabs such that they're ordered as All and then alphabetical. Will leave the loading symbols for another time.

**Pull request merged**
