### PR TITLE
Regional tab performance improvements

### PR DESCRIPTION
**Pull request by rmbielby**
Some adjustments to the regional_analysis script to hopefully improve… performance. Basically pulls the data frame creation out of the individual map/text/table functions that were all repeating the same calculations and into it's own function that's just run once per filter selection.

Not sure it's had that much effect, but should streamline things a little and at least reduces code repetition.

### CODE REVIEW

**Comment by chfoster** [comment]
So in the text, the results have changed - is this correct and expected?

**Comment by rmbielby** [comment]
> So in the text, the results have changed - is this correct and expected?

So this relates to the question I asked at the end of last week I think about why the summary text stats didn't match up with the table stats (probably on Teams). I assumed they should match, so updated the code such that the text now lines up with what's in the tables. Adding in the extra context I've picked up from our discussions yesterday afternoon, I think what was happening was that the code was replacing the regional table data with the sum's from the sankey regional flow data, but the text was still using the original table data. The change to the text that I made last week means that the text, table and sankey should all have the same counts underlying them.

**Comment by chfoster** [comment]
> > So in the text, the results have changed - is this correct and expected?
> 
> So this relates to the question I asked at the end of last week I think about why the summary text stats didn't match up with the table stats (probably on Teams). I assumed they should match, so updated the code such that the text now lines up with what's in the tables. Adding in the extra context I've picked up from our discussions yesterday afternoon, I think what was happening was that the code was replacing the regional table data with the sum's from the sankey regional flow data, but the text was still using the original table data. The change to the text that I made last week means that the text, table and sankey should all have the same counts underlying them.

That's great :) Can we remove NA's from the text and then I think it's ready?

**Comment by rmbielby** [comment]
> > > So in the text, the results have changed - is this correct and expected?
> > 
> > 
> > So this relates to the question I asked at the end of last week I think about why the summary text stats didn't match up with the table stats (probably on Teams). I assumed they should match, so updated the code such that the text now lines up with what's in the tables. Adding in the extra context I've picked up from our discussions yesterday afternoon, I think what was happening was that the code was replacing the regional table data with the sum's from the sankey regional flow data, but the text was still using the original table data. The change to the text that I made last week means that the text, table and sankey should all have the same counts underlying them.
> 
> That's great :) Can we remove NA's from the text and then I think it's ready?

Hmm, just spotted that the top end in the text is always "increased" whether the maximum percentage is positive or negative and the bottom end is always "decreased". Will add something to make the increase/decrease text dynamic, whilst I'm dealing with the NAs.

**Comment by chfoster** [comment]
> > > > So in the text, the results have changed - is this correct and expected?
> > > 
> > > 
> > > So this relates to the question I asked at the end of last week I think about why the summary text stats didn't match up with the table stats (probably on Teams). I assumed they should match, so updated the code such that the text now lines up with what's in the tables. Adding in the extra context I've picked up from our discussions yesterday afternoon, I think what was happening was that the code was replacing the regional table data with the sum's from the sankey regional flow data, but the text was still using the original table data. The change to the text that I made last week means that the text, table and sankey should all have the same counts underlying them.
> > 
> > 
> > That's great :) Can we remove NA's from the text and then I think it's ready?
> 
> Hmm, just spotted that the top end in the text is always "increased" whether the maximum percentage is positive or negative and the bottom end is always "decreased". Will add something to make the increase/decrease text dynamic, whilst I'm dealing with the NAs.

That would be great thank you! :)

**Pull request merged**
